### ISSUE TITLE
AttributeError: 'RelationNetLRP' object has no attribute 'lrptraining'

### ISSUE THREAD

**Issue by Haoqing-Wang** [SunJiamei/few-shot-lrp-guided#1]
relationnet.py文件的第267行的变量self.lrptraining没有定义直接用了，是不是一直是True

**Comment by SunJiamei** [comment]
是的， 抱歉这里这个self.lrptraining是之前调试用的，因为已经重新定义了整个网络，这个参数不需要了。谢谢找到这个bug

**Comment by SunJiamei** [comment]
I have updated the relationnet.py. The `self.lrptraining' should be `self.training'. We only use lrp-inference during the training. _

**Comment by SunJiamei** [comment]
This issue has been addressed and I will close it.
